BookStoreWeb/BookStoreWeb/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace BookStoreWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("Admin")]
    [Authorize(Roles = "admin")]
    public class HomeController : Controller
    {
        [Route("Admin-Home")]
        // GET: HomeController
        public ActionResult Index()
        {
            return View();
        }
        [Route("Admin-Details/{id}")]
        // GET: HomeController/Details/5
        public ActionResult Details(int id)
        {
            return View(id);
        }

        // GET: HomeController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: HomeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: HomeController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: HomeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: HomeController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: HomeController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

BookStoreWeb/BookStoreWeb/Areas/Financial/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace BookStoreWeb.Areas.Financial.Controllers
{
    [Area("Financial")]
    [Route("Financial")]
    [Authorize(Roles ="admin")]
    public class HomeController : Controller
    {
        [Route("Financial-Home")]
        // GET: HomeController
        public ActionResult Index()
        {
            return View();
        }
        [Route("Financial-Details/{id}")]
        // GET: HomeController/Details/5
        public ActionResult Details(int id)
        {
            return View(id);
        }

        // GET: HomeController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: HomeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: HomeController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: HomeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: HomeController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: HomeController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

BookStoreWeb/BookStoreWeb/Components/TopBooksViewComponent.cs
using BookStoreWeb.Repository;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace BookStoreWeb.Components
{
    public class TopBooksViewComponent: ViewComponent
    {
        private readonly IBookRepository _iBookRepository = null;
        public TopBooksViewComponent(IBookRepository iBookRepository)
        {
            _iBookRepository = iBookRepository;
        }
        public async Task<IViewComponentResult> InvokeAsync(int top)
        {
            return View(await _iBookRepository.GetTopBooks(top));
        }
    }
}

BookStoreWeb/BookStoreWeb/Controllers/HomeController.cs
using BookStoreWeb.Models;
using BookStoreWeb.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System.Collections.Generic;
using System.Dynamic;
using System.Threading.Tasks;

namespace BookStoreWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly IConfiguration _config;
        private readonly IUserService _userService;
        public readonly IEmailService _emailService;

        public HomeController(IConfiguration config, IUserService userService, IEmailService emailService)
        {
            _config = config;
            _userService = userService;
            _emailService = emailService;
        }
        [Route("")]
        public async Task<ViewResult> Index()
        {
            //...........send email...............................................//
            //TestMailOptionsVM testMailOptionsVM = new TestMailOptionsVM
            //{
            //    mailToAddresses = new List<string> { "aaa@hotmail.com" },
            //    placeHolder = new List<KeyValuePair<string, string>>
            //    {
            //        new KeyValuePair<string, string>("{{clientName}}" ,"aaa aaa")
            //    }

            //};
            //await _emailService.SendTestMail(testMailOptionsVM);
            //...........................end.........................................//

            //..............use UserService class.................................//

            var signInUserId = _userService.GetUserId();
            var isUserSignIn = _userService.IsUserAuthenticated();

            //..........................end..........................................//

            //...........read settings from appsettings...........................//
            var key1 = _config["TestObj:Key1"]; //...read from appsettings.json
            var Key3Key1 = _config["TestObj:Key3:Key3Key1"]; //...read from appsettings.json

            //..to read anything else from string
            var testNewBookAlert = _config.GetValue<bool>("TestDisplayNewBookAlertInServerSideCode");

            //....to read configration from appsettings.json and bind it to model class
            //...see TestBindConfigurationToObject class , and appsettings.json
            TestBindConfigurationToObject obj = new TestBindConfigurationToObject();
            _config.Bind("TestAlertInClientSideCode", obj);
            var check = obj.NewBookAlert;
            var alert = obj.BookAlert;
            //.............................end..................................................//


            return View();
        }
        [Route("About-Us")]
        public ViewResult AboutUs()
        {
            return View();
        }
        [Route("Contact-Us")]
        public ViewResult ContactUs()
        {
            return View();
        }
    }
}

BookStoreWeb/BookStoreWeb/Views/Home/AboutUs.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AboutUs</title>
</head>
<body>
    <h1>home > About Us</h1>
</body>
</html>

BookStoreWeb/BookStoreWeb/Views/Home/ContactUs.cshtml
@{
    ViewData["Title"] = "Contact Us";
}

@section breadcrumb{
<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb text-bg-light">
        @*        <li class="breadcrumb-item"><a href="#">Home</a></li>*@
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>
}
<h1>home > Contact Us</h1>

BookStoreWeb/BookStoreWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

@section breadcrumb{
<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb text-bg-light">
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>
}

<div class="p-5 bg-light rounded-3 text-center">
    <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">Custom jumbotron</h1>
        <p class="fs-4 text-muted">Using a series of utilities, you can create this jumbotron, just like the one in previous versions of Bootstrap. Check out the examples below for how you can remix and restyle it to your liking.</p>
        <button class="btn btn-outline-primary btn-lg" type="button">Example button</button>
    </div>
</div>


<div class="container">
    <h3 class="text-center display-5 fw-bold py-3">Newest Books</h3>
    <div class="row row-cols-1 row-cols-md-3 g-4">
        <vc:top-books top="3">

        </vc:top-books>
    </div>

    @if (_iConfiguration.GetValue<bool>("TestAlertInClientSideCode:NewBookAlert"))
    {
        <div class="alert alert-info m-4" role="alert">
            @(_iConfiguration.GetValue<string>("TestAlertInClientSideCode:BookAlert"))
        </div>
    }

</div>